bestyear_main:
    resource: "@BestyearMainBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: BestyearUserBundle:Security:login }
 
login_check:
    pattern:   /login_check
 
logout:
    pattern:   /logout