parameters:
#    bestyear_main.example.class: Bestyear\MainBundle\Example

services:
#    bestyear_main.example:
#        class: %bestyear_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
