parameters:
#    bestyear_user.example.class: Bestyear\UserBundle\Example

services:
    bestyear_user.registration.form.type:
        class: Bestyear\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: bestyear_user_registration }
