parameters:
#    bestyear_user.example.class: Bestyear\UserBundle\Example

services:
    bestyear_user.registration.form.type:
        class: Bestyear\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: bestyear_user_registration }
            
    bestyear_user.profile.form.type:
        class: Bestyear\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: bestyear_user_profile }

    bestyear_user.password_changed:
        class: Bestyear\UserBundle\EventListener\PasswordChangedListener
        arguments: [ @router ]
        tags:
            - { name: kernel.event_subscriber }

    bestyear_user.password_reset:
        class: Bestyear\UserBundle\EventListener\PasswordResetListener
        arguments: [ @router ]
        tags:
            - { name: kernel.event_subscriber }